### ISSUE TITLE
Could you also upload a xcodeproj file so that I can import and run it successfully with Xcode

### ISSUE THREAD

**Issue by likeconan** [ziyangwang007/Realtime-Openpose-on-iOS-with-Double-Robot#1]
I copied your all files into my Xcode Test Project but failed to run it because some import issues (Sorry that I'm new to xcode)
<img width="270" alt="image" src="https://github.com/ziyangwang007/Realtime-Openpose-on-iOS-with-Double-Robot/assets/12960160/58f9fe6e-3ac3-4dab-b4b5-a9fba80ddb74">

**Comment by ziyangwang007** [comment]
Hi, 

sorry that this project was developed 4 or 5 years ago when I was a Master student.

I really forget about ios development, but I recommend you to have a look at this project first: 

https://github.com/infocom-tpo/SwiftOpenPose

If my memory was correct, i use openpose, and then use this SDK to conttol robot:

https://github.com/doublerobotics/Basic-Control-SDK-iOS

Thanks.

**Comment by ziyangwang007** [comment]
also try ChatGPT

**Comment by likeconan** [comment]
Thanks a lot. I found another one now.
